### ISSUE TITLE
Dots over slider.

### ISSUE THREAD

**Issue by vision34** [metafizzy/flickity-docs#20]
Hi,

i would like to place dots not under the container, but over. how is it possible?

Best regards,
Radek

**Comment by desandro** [comment]
You can do this with CSS. See http://flickity.metafizzy.co/style.html#page-dots

``` css
/* position dots in gallery */
.flickity-page-dots {
  bottom: 0px;
}
```
